### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Nidev-lab** [nestor-labiuk/menu-arabe#49]
## Proceso

1. Ingrese a la pagina.
2. Entre a la seccion "Logueo" y "Registrate"
 
## Resultado esperado.

Encontrar los respectivos formularios en condiciones y sin espacios.

## Resultado actual

Debajo del formulario de "logueo" y "registrate" se encuentra un amplio espacio vacio.

## Captura

![image](https://github.com/nestor-labiuk/menu-arabe/assets/53904695/e6d3a57a-6953-43eb-afb1-e138904c221e)

## Posible solucion
 
Quitar el height asignado "Logueo"
![image](https://github.com/nestor-labiuk/menu-arabe/assets/53904695/ef4f7c3f-a511-447d-a9c7-1a3ac8d03481)

Quitar el height asignado "registro"
![image](https://github.com/nestor-labiuk/menu-arabe/assets/53904695/9928276c-084b-4636-ad20-adda9c6e55e2)

resultado:

![image](https://github.com/nestor-labiuk/menu-arabe/assets/53904695/fcac2094-b097-42be-8897-3384d9dabf64)

![image](https://github.com/nestor-labiuk/menu-arabe/assets/53904695/5ac98206-50c8-4db0-99c8-c9f1a0c0aa32)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by qpmjcv** [comment]
Los espacios innecesarios corregidos.
